### ISSUE TITLE
Blocking Call in Plex Recently Added Integration Causes Performance Issues in Home Assistant

### ISSUE THREAD

**Issue by cloudbr34k84** [NemesisRE/sensor.plex_recently_added#9]
Describe the Bug
The custom integration plex_recently_added is making a blocking call to os.listdir() inside the Home Assistant event loop, which leads to performance issues. This causes delays in the system due to the synchronous operation being executed in an asynchronous environment, as outlined by the Home Assistant warning system.

The Error
```
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 3:39:59 pm (5 occurrences)
Last logged: 3:40:10 pm

Detected blocking call to listdir with args ('/config/www/upcoming-media-card-images/plex/Recently_Added_Movies/',) inside the event loop by custom integration 'plex_recently_added' at custom_components/plex_recently_added/sensor.py, line 292: os.listdir(directory))) (offender: /config/custom_components/plex_recently_added/sensor.py, line 292: os.listdir(directory)))), please create a bug report at https://github.com/NemesisRE/sensor.plex_recently_added For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/plex_recently_added/sensor.py", line 292, in async_update
    os.listdir(directory)))
```

Indicate if you followed all steps in the [troubleshooting doc](https://github.com/NemesisRE/upcoming-media-card/blob/master/troubleshooting.md)
Yes, I have followed the troubleshooting guide.

What data does the sensor display if any?
The sensor displays the recently added media from Plex correctly. However, the blocking call is causing performance issues within Home Assistant.

What displays when visiting the API URL from the troubleshooting guide?
The API URL displays the correct JSON data for recently added Plex media, including the titles and metadata.

Does the default Home Assistant Plex component work for you?
Yes, the default Plex component in Home Assistant works as expected, with no issues related to connectivity or performance.

Home Assistant Version
I am running Home Assistant version [insert your version here].

Additional Context
The integration needs to be updated to use asynchronous operations for file system interactions to prevent blocking the event loop. The current blocking call to os.listdir() is causing performance degradation, and a refactor to asynchronous handling is needed.

**Comment by mkanet** [comment]
Hi @cloudbr34k84  Are you sure you're using the right repo? This fork for Plex Recently Added hasn't been updated In a long time. Please try the original/official repo; which is updated regularly:

https://github.com/custom-components/sensor.plex_recently_added
If you still see the same issue with the official repo, please open an issue at the correct repo.

**Comment by cloudbr34k84** [comment]
> Hi @cloudbr34k84  Are you sure you're using the right repo? This fork for Plex Recently Added hasn't been updated In a long time. Please try the original/official repo; which is updated regularly:
> 
> https://github.com/custom-components/sensor.plex_recently_added
> If you still see the same issue with the official repo, please open an issue at the correct repo.

I think I posted in the wrong repo. Sorry man!
